#!/bin/sh
set -ex

apt-get update
apt-get install --yes \
  ca-certificates=${CA_CERTIFICATES_VERSION} \
  curl

# Install AWR
useradd -r -d /opt/alertmanager-webhook-servicenow awsn

mkdir -p /opt/alertmanager-webhook-servicenow
mv /alertmanager-webhook-servicenow /opt/alertmanager-webhook-servicenow

chown -R awsn /opt/alertmanager-webhook-servicenow

# Install confd
curl -sSL \
  -o /resources/confd_binary \
  https://github.com/kelseyhightower/confd/releases/download/v${CONFD_VERSION}/confd-${CONFD_VERSION}-linux-amd64

mkdir -p /opt/confd/bin
mkdir -p /etc/confd
mv /resources/confd_binary /opt/confd/bin/confd
chmod +x /opt/confd/bin/confd
ln -s /opt/confd/bin/confd /usr/local/bin/confd

mv /resources/confd/conf.d /etc/confd
mv /resources/confd/templates /etc/confd

# Add entrypoint
mv /resources/entrypoint /

# Clean
apt-get remove --purge curl --yes
apt-get autoremove --purge --yes
apt-get clean --yes

# CIS Benchmarking
sed -i 's/^PASS_MAX_DAYS.*$/PASS_MAX_DAYS   60/g' /etc/login.defs
sed -i 's/^PASS_MIN_DAYS.*$/PASS_MIN_DAYS   7/g' /etc/login.defs
sed -i 's/^UMASK.*$/UMASK   027/g' /etc/login.defs
